version: "3.8"

services:
  ##########
  # Initialisers

  # These are "initial" Docker images, setting basics like locales
  # "app" user and some minimal required packages.

  init:
    image: base:init
    build:
      context: init
      dockerfile: init.dockerfile

  minecraft-downloads:
    image: base:minecraft-downloads
    build:
      context: init
      dockerfile: minecraft-downloads.dockerfile
    depends_on:
      - init

  java11:
    image: base:java11
    build:
      context: .
      dockerfile: java11.dockerfile
    depends_on:
      - init

  java16:
    image: base:java16
    build:
      context: .
      dockerfile: java16.dockerfile
    depends_on:
      - init

  java17:
    image: base:java17
    build:
      context: .
      dockerfile: java17.dockerfile
    depends_on:
      - init

  spigot11:
    image: spigot:${VERSION:-1.15.2}
    build:
      args:
        VERSION: ${VERSION:-1.15.2}
      context: .
      dockerfile: spigot11.dockerfile
    depends_on:
      - java11
    ports:
      - ${PORT:-25565}:${PORT_INSIDE:-25565}
    volumes:
      - ${DIR:-/home/minecraft/minecraft}:/minecraft
    tty: true

  spigot16:
    image: spigot:${VERSION:-1.17.1}
    build:
      args:
        VERSION: ${VERSION:-1.17.1}
      context: .
      dockerfile: spigot16.dockerfile
    depends_on:
      - java16
    ports:
      - ${PORT:-25565}:${PORT_INSIDE:-25565}
    volumes:
      - ${DIR:-/home/minecraft/minecraft}:/minecraft
    tty: true

  forge16:
    image: forge:${VERSION:-1.17.1}
    build:
      args:
        VERSION: ${VERSION:-1.17.1}
        BUILD_NUM: ${BUILD_NUM:-37.1.1}
      context: .
      dockerfile: forge16.dockerfile
    depends_on:
      - minecraft-downloads
      - java16
    ports:
      - ${PORT:-25565}:${PORT_INSIDE:-25565}
    volumes:
      - ${DIR:-/home/minecraft/minecraft}:/minecraft
    tty: true

  forge17:
    image: forge:${VERSION:-1.18.1}
    build:
      args:
        VERSION: ${VERSION:-1.18.1}
        BUILD_NUM: ${BUILD_NUM:-39.0.66}
      context: .
      dockerfile: forge17.dockerfile
    depends_on:
      - minecraft-downloads
      - java17
    ports:
      - ${PORT:-25565}:${PORT_INSIDE:-25565}
    volumes:
      - ${DIR:-/home/minecraft/minecraft}:/minecraft
    tty: true

  minecraft:
    image: minecraft_server:${VERSION:-1.15.2}
    build:
      args:
        VERSION: ${VERSION:-1.15.2}
      context: .
      dockerfile: "minecraft-server.dockerfile"
    depends_on:
      - minecraft-downloads
      - java16
    ports:
      - ${PORT:-25565}:${PORT_INSIDE:-25565}
    volumes:
      - ${DIR:-/home/minecraft/minecraft}:/minecraft
    tty: true

  multiverse:
    image: multiverse
    build:
      context: .
      dockerfile: multiverse.dockerfile
    depends_on:
      - init

  worldedit:
    image: worldedit
    build:
      context: .
      dockerfile: worldedit.dockerfile
    depends_on:
      - init

